use crate::models::OperationResult;
use crate::services::PathDiscoveryService;
use serde::Deserialize;
use std::collections::BTreeMap;
use std::fs;
use std::path::PathBuf;

// Loot list template (generated by ModOutput/Source/11_loot.py). Embedded at build time so
// no external resource path is needed.
const TEMPLATE: &str = include_str!("../loot_template.json");

#[derive(Deserialize)]
struct Entry {
    #[serde(rename = "ref")]
    reference: String,
    level: i64,
    count: i64,
}

#[derive(Deserialize)]
struct ListDef {
    target: String,
    entries: Vec<Entry>,
}

#[derive(Deserialize)]
struct JunkTarget {
    target: String,
}

#[derive(Deserialize)]
struct Template {
    junk_ll: String,
    junk_targets: Vec<JunkTarget>,
    categories: BTreeMap<String, Vec<ListDef>>,
}

/// Per-category scarcity as RobCo ChanceNone (inverted: 0 = always drops, 95 = almost never).
/// Sent from the launcher's per-category sliders.
#[derive(Deserialize)]
pub struct LootChances {
    pub guns: u32,
    pub meds: u32,
    pub food: u32,
    pub drink: u32,
    pub ammo: u32,
    pub junk: u32,
}

pub struct LootScarcity;

impl LootScarcity {
    /// Regenerate FallenWorldCrafting_Loot.ini in the mod's RobCo folder from the embedded
    /// template + the given per-category scarcity. Called on Play so the sliders take effect.
    pub fn apply(c: &LootChances) -> OperationResult {
        let paths = match PathDiscoveryService::discover() {
            Ok(p) => p,
            Err(e) => return fail(format!("Cannot determine mods folder: {}", e)),
        };
        let tmpl: Template = match serde_json::from_str(TEMPLATE) {
            Ok(t) => t,
            Err(e) => return fail(format!("Bad loot template: {}", e)),
        };

        let dest = PathBuf::from(&paths.mods_folder)
            .join("FallenWorldCraftingFramework")
            .join("F4SE")
            .join("Plugins")
            .join("RobCo_Patcher")
            .join("leveledList");
        if let Err(e) = fs::create_dir_all(&dest) {
            return fail(format!("Cannot create RobCo folder: {}", e));
        }

        let ini = build_ini(&tmpl, c);
        let file = dest.join("FallenWorldCrafting_Loot.ini");
        match fs::write(&file, ini) {
            Ok(_) => OperationResult {
                success: true,
                message: format!("Loot scarcity applied to {}", file.display()),
            },
            Err(e) => fail(format!("Cannot write loot INI: {}", e)),
        }
    }
}

fn chance_for(cat: &str, c: &LootChances) -> u32 {
    let v = match cat {
        "guns" => c.guns,
        "meds" => c.meds,
        "food" => c.food,
        "drink" => c.drink,
        "ammo" => c.ammo,
        _ => 0,
    };
    v.min(95)
}

fn build_ini(t: &Template, c: &LootChances) -> String {
    let mut out = String::from(
        "// Fallen World Crafting - Hardcore Loot (launcher-generated)\n\
         // RobCo Patcher: thins vanilla world loot (clear + re-add at reduced chance).\n\
         // chance inverted: 0=100%, 78~=22% appear. Do not edit by hand - the launcher\n\
         // overwrites this file on Play.\n\n",
    );
    for (cat, lists) in &t.categories {
        let ch = chance_for(cat, c);
        out.push_str(&format!("// ---- {} (~{}% appear) ----\n", cat.to_uppercase(), 100 - ch));
        for l in lists {
            out.push_str(&format!("filterByLLs={}:clear=yes\n", l.target));
            let adds: Vec<String> = l
                .entries
                .iter()
                .map(|e| format!("{}~{}~{}~{}", e.reference, e.level, e.count, ch))
                .collect();
            if !adds.is_empty() {
                out.push_str(&format!(
                    "filterByLLs={}:addToLLs={}\n",
                    l.target,
                    adds.join(", ")
                ));
            }
        }
        out.push('\n');
    }
    let jch = c.junk.min(95);
    out.push_str(&format!("// ---- JUNK ON ENEMIES (~{}% appear) ----\n", 100 - jch));
    for jt in &t.junk_targets {
        out.push_str(&format!(
            "filterByLLs={}:addToLLs={}~1~1~{}\n",
            jt.target, t.junk_ll, jch
        ));
    }
    out
}

fn fail(msg: String) -> OperationResult {
    OperationResult { success: false, message: msg }
}
